// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { addMedicalRecord, bookAppointment, callPatient, checkIn, completeConsultation, getCurrentUser, getDoctorAppointments, getDoctorQueue, getDoctors, getMedicalRecords, getPatientAppointments, getPatientById, getUnreadNotifications, login, logout, markAllAsRead, type Options, register, registerPatient, searchPatients, subscribe, updateAppointmentStatus, updatePatient } from '../sdk.gen';
import type { AddMedicalRecordData, AddMedicalRecordResponse, BookAppointmentData, BookAppointmentResponse, CallPatientData, CallPatientResponse, CheckInData, CheckInResponse, CompleteConsultationData, CompleteConsultationResponse, GetCurrentUserData, GetCurrentUserResponse, GetDoctorAppointmentsData, GetDoctorAppointmentsResponse, GetDoctorQueueData, GetDoctorQueueResponse, GetDoctorsData, GetDoctorsResponse, GetMedicalRecordsData, GetMedicalRecordsResponse, GetPatientAppointmentsData, GetPatientAppointmentsResponse, GetPatientByIdData, GetPatientByIdResponse, GetUnreadNotificationsData, GetUnreadNotificationsResponse, LoginData, LoginResponse, LogoutData, MarkAllAsReadData, RegisterData, RegisterPatientData, RegisterPatientResponse, RegisterResponse, SearchPatientsData, SearchPatientsResponse, SubscribeData, SubscribeResponse, UpdateAppointmentStatusData, UpdateAppointmentStatusResponse, UpdatePatientData, UpdatePatientResponse } from '../types.gen';

export const completeConsultationMutation = (options?: Partial<Options<CompleteConsultationData>>): UseMutationOptions<CompleteConsultationResponse, AxiosError<DefaultError>, Options<CompleteConsultationData>> => {
    const mutationOptions: UseMutationOptions<CompleteConsultationResponse, AxiosError<DefaultError>, Options<CompleteConsultationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await completeConsultation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const callPatientMutation = (options?: Partial<Options<CallPatientData>>): UseMutationOptions<CallPatientResponse, AxiosError<DefaultError>, Options<CallPatientData>> => {
    const mutationOptions: UseMutationOptions<CallPatientResponse, AxiosError<DefaultError>, Options<CallPatientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await callPatient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getPatientByIdQueryKey = (options: Options<GetPatientByIdData>) => createQueryKey('getPatientById', options);

export const getPatientByIdOptions = (options: Options<GetPatientByIdData>) => queryOptions<GetPatientByIdResponse, AxiosError<DefaultError>, GetPatientByIdResponse, ReturnType<typeof getPatientByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientByIdQueryKey(options)
});

export const updatePatientMutation = (options?: Partial<Options<UpdatePatientData>>): UseMutationOptions<UpdatePatientResponse, AxiosError<DefaultError>, Options<UpdatePatientData>> => {
    const mutationOptions: UseMutationOptions<UpdatePatientResponse, AxiosError<DefaultError>, Options<UpdatePatientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePatient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateAppointmentStatusMutation = (options?: Partial<Options<UpdateAppointmentStatusData>>): UseMutationOptions<UpdateAppointmentStatusResponse, AxiosError<DefaultError>, Options<UpdateAppointmentStatusData>> => {
    const mutationOptions: UseMutationOptions<UpdateAppointmentStatusResponse, AxiosError<DefaultError>, Options<UpdateAppointmentStatusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateAppointmentStatus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const checkInMutation = (options?: Partial<Options<CheckInData>>): UseMutationOptions<CheckInResponse, AxiosError<DefaultError>, Options<CheckInData>> => {
    const mutationOptions: UseMutationOptions<CheckInResponse, AxiosError<DefaultError>, Options<CheckInData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await checkIn({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerPatientMutation = (options?: Partial<Options<RegisterPatientData>>): UseMutationOptions<RegisterPatientResponse, AxiosError<DefaultError>, Options<RegisterPatientData>> => {
    const mutationOptions: UseMutationOptions<RegisterPatientResponse, AxiosError<DefaultError>, Options<RegisterPatientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerPatient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMedicalRecordsQueryKey = (options: Options<GetMedicalRecordsData>) => createQueryKey('getMedicalRecords', options);

export const getMedicalRecordsOptions = (options: Options<GetMedicalRecordsData>) => queryOptions<GetMedicalRecordsResponse, AxiosError<DefaultError>, GetMedicalRecordsResponse, ReturnType<typeof getMedicalRecordsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMedicalRecords({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMedicalRecordsQueryKey(options)
});

export const addMedicalRecordMutation = (options?: Partial<Options<AddMedicalRecordData>>): UseMutationOptions<AddMedicalRecordResponse, AxiosError<DefaultError>, Options<AddMedicalRecordData>> => {
    const mutationOptions: UseMutationOptions<AddMedicalRecordResponse, AxiosError<DefaultError>, Options<AddMedicalRecordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addMedicalRecord({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const markAllAsReadMutation = (options?: Partial<Options<MarkAllAsReadData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<MarkAllAsReadData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<MarkAllAsReadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await markAllAsRead({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, AxiosError<DefaultError>, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, AxiosError<DefaultError>, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, AxiosError<DefaultError>, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, AxiosError<DefaultError>, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const bookAppointmentMutation = (options?: Partial<Options<BookAppointmentData>>): UseMutationOptions<BookAppointmentResponse, AxiosError<DefaultError>, Options<BookAppointmentData>> => {
    const mutationOptions: UseMutationOptions<BookAppointmentResponse, AxiosError<DefaultError>, Options<BookAppointmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await bookAppointment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDoctorQueueQueryKey = (options: Options<GetDoctorQueueData>) => createQueryKey('getDoctorQueue', options);

export const getDoctorQueueOptions = (options: Options<GetDoctorQueueData>) => queryOptions<GetDoctorQueueResponse, AxiosError<DefaultError>, GetDoctorQueueResponse, ReturnType<typeof getDoctorQueueQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDoctorQueue({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDoctorQueueQueryKey(options)
});

export const searchPatientsQueryKey = (options: Options<SearchPatientsData>) => createQueryKey('searchPatients', options);

export const searchPatientsOptions = (options: Options<SearchPatientsData>) => queryOptions<SearchPatientsResponse, AxiosError<DefaultError>, SearchPatientsResponse, ReturnType<typeof searchPatientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchPatients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchPatientsQueryKey(options)
});

export const getUnreadNotificationsQueryKey = (options?: Options<GetUnreadNotificationsData>) => createQueryKey('getUnreadNotifications', options);

export const getUnreadNotificationsOptions = (options?: Options<GetUnreadNotificationsData>) => queryOptions<GetUnreadNotificationsResponse, AxiosError<DefaultError>, GetUnreadNotificationsResponse, ReturnType<typeof getUnreadNotificationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUnreadNotifications({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUnreadNotificationsQueryKey(options)
});

export const subscribeQueryKey = (options?: Options<SubscribeData>) => createQueryKey('subscribe', options);

export const subscribeOptions = (options?: Options<SubscribeData>) => queryOptions<SubscribeResponse, AxiosError<DefaultError>, SubscribeResponse, ReturnType<typeof subscribeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await subscribe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: subscribeQueryKey(options)
});

export const getDoctorsQueryKey = (options?: Options<GetDoctorsData>) => createQueryKey('getDoctors', options);

export const getDoctorsOptions = (options?: Options<GetDoctorsData>) => queryOptions<GetDoctorsResponse, AxiosError<DefaultError>, GetDoctorsResponse, ReturnType<typeof getDoctorsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDoctors({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDoctorsQueryKey(options)
});

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) => createQueryKey('getCurrentUser', options);

export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) => queryOptions<GetCurrentUserResponse, AxiosError<DefaultError>, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserQueryKey(options)
});

export const getPatientAppointmentsQueryKey = (options: Options<GetPatientAppointmentsData>) => createQueryKey('getPatientAppointments', options);

export const getPatientAppointmentsOptions = (options: Options<GetPatientAppointmentsData>) => queryOptions<GetPatientAppointmentsResponse, AxiosError<DefaultError>, GetPatientAppointmentsResponse, ReturnType<typeof getPatientAppointmentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientAppointments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientAppointmentsQueryKey(options)
});

export const getDoctorAppointmentsQueryKey = (options: Options<GetDoctorAppointmentsData>) => createQueryKey('getDoctorAppointments', options);

export const getDoctorAppointmentsOptions = (options: Options<GetDoctorAppointmentsData>) => queryOptions<GetDoctorAppointmentsResponse, AxiosError<DefaultError>, GetDoctorAppointmentsResponse, ReturnType<typeof getDoctorAppointmentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDoctorAppointments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDoctorAppointmentsQueryKey(options)
});
