// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getAppointmentsDoctorByDoctorId, getAuthMe, getDoctors, getPatientsById, getPatientsByIdRecords, getPatientsSearch, getQueueDoctorByDoctorId, type Options, postAppointments, postAuthLogin, postAuthLogout, postAuthRegister, postPatients, postPatientsByIdRecords, postQueueCheckIn, putAppointmentsByIdStatus, putPatientsById, putQueueByIdCall, putQueueByIdComplete } from '../sdk.gen';
import type { GetAppointmentsDoctorByDoctorIdData, GetAppointmentsDoctorByDoctorIdResponse, GetAuthMeData, GetAuthMeResponse, GetDoctorsData, GetDoctorsResponse, GetPatientsByIdData, GetPatientsByIdRecordsData, GetPatientsByIdRecordsResponse, GetPatientsByIdResponse, GetPatientsSearchData, GetPatientsSearchResponse, GetQueueDoctorByDoctorIdData, GetQueueDoctorByDoctorIdResponse, PostAppointmentsData, PostAppointmentsResponse, PostAuthLoginData, PostAuthLoginResponse, PostAuthLogoutData, PostAuthRegisterData, PostAuthRegisterError, PostAuthRegisterResponse, PostPatientsByIdRecordsData, PostPatientsByIdRecordsResponse, PostPatientsData, PostPatientsResponse, PostQueueCheckInData, PostQueueCheckInResponse, PutAppointmentsByIdStatusData, PutAppointmentsByIdStatusResponse, PutPatientsByIdData, PutPatientsByIdResponse, PutQueueByIdCallData, PutQueueByIdCallResponse, PutQueueByIdCompleteData, PutQueueByIdCompleteResponse } from '../types.gen';

/**
 * Authenticate Operator Node
 *
 * Verifies staff credentials and returns a secure HttpOnly session cookie containing the JWT.
 */
export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, AxiosError<DefaultError>, Options<PostAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginResponse, AxiosError<DefaultError>, Options<PostAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Terminate Session
 *
 * Evicts the JWT cookie and publishes a logout event to the audit trail.
 */
export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, AxiosError<DefaultError>, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register Staff Node
 *
 * Creates a new clinic staff account. Restricted to ROLE_ADMIN.
 */
export const postAuthRegisterMutation = (options?: Partial<Options<PostAuthRegisterData>>): UseMutationOptions<PostAuthRegisterResponse, AxiosError<PostAuthRegisterError>, Options<PostAuthRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRegisterResponse, AxiosError<PostAuthRegisterError>, Options<PostAuthRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) => createQueryKey('getAuthMe', options);

/**
 * Get Current Profile
 *
 * Returns details of the currently authenticated operator.
 */
export const getAuthMeOptions = (options?: Options<GetAuthMeData>) => queryOptions<GetAuthMeResponse, AxiosError<DefaultError>, GetAuthMeResponse, ReturnType<typeof getAuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthMeQueryKey(options)
});

/**
 * Register Patient (Intake)
 *
 * Performs patient intake and demographic registration. SSN is automatically masked.
 */
export const postPatientsMutation = (options?: Partial<Options<PostPatientsData>>): UseMutationOptions<PostPatientsResponse, AxiosError<DefaultError>, Options<PostPatientsData>> => {
    const mutationOptions: UseMutationOptions<PostPatientsResponse, AxiosError<DefaultError>, Options<PostPatientsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postPatients({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPatientsByIdQueryKey = (options: Options<GetPatientsByIdData>) => createQueryKey('getPatientsById', options);

/**
 * Get Patient Details
 *
 * Retrieves demographic details. Cached in Redis for 1 hour.
 */
export const getPatientsByIdOptions = (options: Options<GetPatientsByIdData>) => queryOptions<GetPatientsByIdResponse, AxiosError<DefaultError>, GetPatientsByIdResponse, ReturnType<typeof getPatientsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientsByIdQueryKey(options)
});

/**
 * Update Patient Profile
 *
 * Updates details and evicts the corresponding Redis patient cache entry.
 */
export const putPatientsByIdMutation = (options?: Partial<Options<PutPatientsByIdData>>): UseMutationOptions<PutPatientsByIdResponse, AxiosError<DefaultError>, Options<PutPatientsByIdData>> => {
    const mutationOptions: UseMutationOptions<PutPatientsByIdResponse, AxiosError<DefaultError>, Options<PutPatientsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putPatientsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPatientsSearchQueryKey = (options: Options<GetPatientsSearchData>) => createQueryKey('getPatientsSearch', options);

/**
 * Search Patients
 *
 * Performs case-insensitive search by patient name.
 */
export const getPatientsSearchOptions = (options: Options<GetPatientsSearchData>) => queryOptions<GetPatientsSearchResponse, AxiosError<DefaultError>, GetPatientsSearchResponse, ReturnType<typeof getPatientsSearchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientsSearch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientsSearchQueryKey(options)
});

export const getPatientsByIdRecordsQueryKey = (options: Options<GetPatientsByIdRecordsData>) => createQueryKey('getPatientsByIdRecords', options);

/**
 * Get Patient Consultation History
 *
 * Retrieves all consultation records for the patient, ordered by date descending. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const getPatientsByIdRecordsOptions = (options: Options<GetPatientsByIdRecordsData>) => queryOptions<GetPatientsByIdRecordsResponse, AxiosError<DefaultError>, GetPatientsByIdRecordsResponse, ReturnType<typeof getPatientsByIdRecordsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPatientsByIdRecords({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPatientsByIdRecordsQueryKey(options)
});

/**
 * Add Medical Record
 *
 * Appends a consultation record. Custom assessments/vitals are sent in a dynamic JSON structure. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const postPatientsByIdRecordsMutation = (options?: Partial<Options<PostPatientsByIdRecordsData>>): UseMutationOptions<PostPatientsByIdRecordsResponse, AxiosError<DefaultError>, Options<PostPatientsByIdRecordsData>> => {
    const mutationOptions: UseMutationOptions<PostPatientsByIdRecordsResponse, AxiosError<DefaultError>, Options<PostPatientsByIdRecordsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postPatientsByIdRecords({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDoctorsQueryKey = (options?: Options<GetDoctorsData>) => createQueryKey('getDoctors', options);

/**
 * List Doctors
 *
 * Lists active registered doctors. Cached in Redis for 1 hour.
 */
export const getDoctorsOptions = (options?: Options<GetDoctorsData>) => queryOptions<GetDoctorsResponse, AxiosError<DefaultError>, GetDoctorsResponse, ReturnType<typeof getDoctorsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDoctors({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDoctorsQueryKey(options)
});

/**
 * Book Appointment
 *
 * Schedules a doctor consultation. Rejects booking if there is a scheduling conflict within a 30-minute window. Uses optimistic locking.
 */
export const postAppointmentsMutation = (options?: Partial<Options<PostAppointmentsData>>): UseMutationOptions<PostAppointmentsResponse, AxiosError<DefaultError>, Options<PostAppointmentsData>> => {
    const mutationOptions: UseMutationOptions<PostAppointmentsResponse, AxiosError<DefaultError>, Options<PostAppointmentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAppointments({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAppointmentsDoctorByDoctorIdQueryKey = (options: Options<GetAppointmentsDoctorByDoctorIdData>) => createQueryKey('getAppointmentsDoctorByDoctorId', options);

/**
 * Get Doctor Schedule
 *
 * Lists appointments assigned to the doctor, ordered by time ascending.
 */
export const getAppointmentsDoctorByDoctorIdOptions = (options: Options<GetAppointmentsDoctorByDoctorIdData>) => queryOptions<GetAppointmentsDoctorByDoctorIdResponse, AxiosError<DefaultError>, GetAppointmentsDoctorByDoctorIdResponse, ReturnType<typeof getAppointmentsDoctorByDoctorIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAppointmentsDoctorByDoctorId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAppointmentsDoctorByDoctorIdQueryKey(options)
});

/**
 * Update Appointment Status
 *
 * Transitions slot state (e.g. to CANCELLED). Rejects transition if slot is already cancelled or completed.
 */
export const putAppointmentsByIdStatusMutation = (options?: Partial<Options<PutAppointmentsByIdStatusData>>): UseMutationOptions<PutAppointmentsByIdStatusResponse, AxiosError<DefaultError>, Options<PutAppointmentsByIdStatusData>> => {
    const mutationOptions: UseMutationOptions<PutAppointmentsByIdStatusResponse, AxiosError<DefaultError>, Options<PutAppointmentsByIdStatusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putAppointmentsByIdStatus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Check-In (Enqueue)
 *
 * Checks in a patient and issues the next sequential token number. Rejects if patient is already active in queue.
 */
export const postQueueCheckInMutation = (options?: Partial<Options<PostQueueCheckInData>>): UseMutationOptions<PostQueueCheckInResponse, AxiosError<DefaultError>, Options<PostQueueCheckInData>> => {
    const mutationOptions: UseMutationOptions<PostQueueCheckInResponse, AxiosError<DefaultError>, Options<PostQueueCheckInData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postQueueCheckIn({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getQueueDoctorByDoctorIdQueryKey = (options: Options<GetQueueDoctorByDoctorIdData>) => createQueryKey('getQueueDoctorByDoctorId', options);

/**
 * Get Doctor Queue Lane
 *
 * Retrieves the active queue list (WAITING and ACTIVE) assigned to the doctor.
 */
export const getQueueDoctorByDoctorIdOptions = (options: Options<GetQueueDoctorByDoctorIdData>) => queryOptions<GetQueueDoctorByDoctorIdResponse, AxiosError<DefaultError>, GetQueueDoctorByDoctorIdResponse, ReturnType<typeof getQueueDoctorByDoctorIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getQueueDoctorByDoctorId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getQueueDoctorByDoctorIdQueryKey(options)
});

/**
 * Call Patient
 *
 * Sets status to ACTIVE. Dispatches async SMS notifying the patient to proceed to the room. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const putQueueByIdCallMutation = (options?: Partial<Options<PutQueueByIdCallData>>): UseMutationOptions<PutQueueByIdCallResponse, AxiosError<DefaultError>, Options<PutQueueByIdCallData>> => {
    const mutationOptions: UseMutationOptions<PutQueueByIdCallResponse, AxiosError<DefaultError>, Options<PutQueueByIdCallData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putQueueByIdCall({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Complete Consultation
 *
 * Sets status to COMPLETED and evicts patient queue item details. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const putQueueByIdCompleteMutation = (options?: Partial<Options<PutQueueByIdCompleteData>>): UseMutationOptions<PutQueueByIdCompleteResponse, AxiosError<DefaultError>, Options<PutQueueByIdCompleteData>> => {
    const mutationOptions: UseMutationOptions<PutQueueByIdCompleteResponse, AxiosError<DefaultError>, Options<PutQueueByIdCompleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putQueueByIdComplete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
