// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddMedicalRecordData, AddMedicalRecordResponses, BookAppointmentData, BookAppointmentResponses, CallPatientData, CallPatientResponses, CheckInData, CheckInResponses, CompleteConsultationData, CompleteConsultationResponses, GetCurrentUserData, GetCurrentUserResponses, GetDoctorAppointmentsData, GetDoctorAppointmentsResponses, GetDoctorQueueData, GetDoctorQueueResponses, GetDoctorsData, GetDoctorsResponses, GetMedicalRecordsData, GetMedicalRecordsResponses, GetPatientAppointmentsData, GetPatientAppointmentsResponses, GetPatientByIdData, GetPatientByIdResponses, GetUnreadNotificationsData, GetUnreadNotificationsResponses, LoginData, LoginResponses, LogoutData, LogoutResponses, MarkAllAsReadData, MarkAllAsReadResponses, RegisterData, RegisterPatientData, RegisterPatientResponses, RegisterResponses, SearchPatientsData, SearchPatientsResponses, SubscribeData, SubscribeResponses, UpdateAppointmentStatusData, UpdateAppointmentStatusResponses, UpdatePatientData, UpdatePatientResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const completeConsultation = <ThrowOnError extends boolean = false>(options: Options<CompleteConsultationData, ThrowOnError>): RequestResult<CompleteConsultationResponses, unknown, ThrowOnError> => (options.client ?? client).put<CompleteConsultationResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/{id}/complete',
    ...options
});

export const callPatient = <ThrowOnError extends boolean = false>(options: Options<CallPatientData, ThrowOnError>): RequestResult<CallPatientResponses, unknown, ThrowOnError> => (options.client ?? client).put<CallPatientResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/{id}/call',
    ...options
});

export const getPatientById = <ThrowOnError extends boolean = false>(options: Options<GetPatientByIdData, ThrowOnError>): RequestResult<GetPatientByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPatientByIdResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}',
    ...options
});

export const updatePatient = <ThrowOnError extends boolean = false>(options: Options<UpdatePatientData, ThrowOnError>): RequestResult<UpdatePatientResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdatePatientResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updateAppointmentStatus = <ThrowOnError extends boolean = false>(options: Options<UpdateAppointmentStatusData, ThrowOnError>): RequestResult<UpdateAppointmentStatusResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateAppointmentStatusResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/appointments/{id}/status',
    ...options
});

export const checkIn = <ThrowOnError extends boolean = false>(options: Options<CheckInData, ThrowOnError>): RequestResult<CheckInResponses, unknown, ThrowOnError> => (options.client ?? client).post<CheckInResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/check-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const registerPatient = <ThrowOnError extends boolean = false>(options: Options<RegisterPatientData, ThrowOnError>): RequestResult<RegisterPatientResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterPatientResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getMedicalRecords = <ThrowOnError extends boolean = false>(options: Options<GetMedicalRecordsData, ThrowOnError>): RequestResult<GetMedicalRecordsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetMedicalRecordsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}/records',
    ...options
});

export const addMedicalRecord = <ThrowOnError extends boolean = false>(options: Options<AddMedicalRecordData, ThrowOnError>): RequestResult<AddMedicalRecordResponses, unknown, ThrowOnError> => (options.client ?? client).post<AddMedicalRecordResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}/records',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const markAllAsRead = <ThrowOnError extends boolean = false>(options?: Options<MarkAllAsReadData, ThrowOnError>): RequestResult<MarkAllAsReadResponses, unknown, ThrowOnError> => (options?.client ?? client).post<MarkAllAsReadResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/notifications/read-all',
    ...options
});

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const bookAppointment = <ThrowOnError extends boolean = false>(options: Options<BookAppointmentData, ThrowOnError>): RequestResult<BookAppointmentResponses, unknown, ThrowOnError> => (options.client ?? client).post<BookAppointmentResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/appointments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getDoctorQueue = <ThrowOnError extends boolean = false>(options: Options<GetDoctorQueueData, ThrowOnError>): RequestResult<GetDoctorQueueResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetDoctorQueueResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/doctor/{doctorId}',
    ...options
});

export const searchPatients = <ThrowOnError extends boolean = false>(options: Options<SearchPatientsData, ThrowOnError>): RequestResult<SearchPatientsResponses, unknown, ThrowOnError> => (options.client ?? client).get<SearchPatientsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/search',
    ...options
});

export const getUnreadNotifications = <ThrowOnError extends boolean = false>(options?: Options<GetUnreadNotificationsData, ThrowOnError>): RequestResult<GetUnreadNotificationsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUnreadNotificationsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/notifications/unread',
    ...options
});

export const subscribe = <ThrowOnError extends boolean = false>(options?: Options<SubscribeData, ThrowOnError>): RequestResult<SubscribeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<SubscribeResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/notifications/subscribe',
    ...options
});

export const getDoctors = <ThrowOnError extends boolean = false>(options?: Options<GetDoctorsData, ThrowOnError>): RequestResult<GetDoctorsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetDoctorsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/doctors',
    ...options
});

export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

export const getPatientAppointments = <ThrowOnError extends boolean = false>(options: Options<GetPatientAppointmentsData, ThrowOnError>): RequestResult<GetPatientAppointmentsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPatientAppointmentsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/appointments/patient/{patientId}',
    ...options
});

export const getDoctorAppointments = <ThrowOnError extends boolean = false>(options: Options<GetDoctorAppointmentsData, ThrowOnError>): RequestResult<GetDoctorAppointmentsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetDoctorAppointmentsResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/appointments/doctor/{doctorId}',
    ...options
});
