// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAppointmentsDoctorByDoctorIdData, GetAppointmentsDoctorByDoctorIdResponses, GetAuthMeData, GetAuthMeErrors, GetAuthMeResponses, GetDoctorsData, GetDoctorsResponses, GetPatientsByIdData, GetPatientsByIdErrors, GetPatientsByIdRecordsData, GetPatientsByIdRecordsResponses, GetPatientsByIdResponses, GetPatientsSearchData, GetPatientsSearchResponses, GetQueueDoctorByDoctorIdData, GetQueueDoctorByDoctorIdResponses, PostAppointmentsData, PostAppointmentsErrors, PostAppointmentsResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostPatientsByIdRecordsData, PostPatientsByIdRecordsResponses, PostPatientsData, PostPatientsErrors, PostPatientsResponses, PostQueueCheckInData, PostQueueCheckInResponses, PutAppointmentsByIdStatusData, PutAppointmentsByIdStatusResponses, PutPatientsByIdData, PutPatientsByIdErrors, PutPatientsByIdResponses, PutQueueByIdCallData, PutQueueByIdCallResponses, PutQueueByIdCompleteData, PutQueueByIdCompleteResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Authenticate Operator Node
 *
 * Verifies staff credentials and returns a secure HttpOnly session cookie containing the JWT.
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Terminate Session
 *
 * Evicts the JWT cookie and publishes a logout event to the audit trail.
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Register Staff Node
 *
 * Creates a new clinic staff account. Restricted to ROLE_ADMIN.
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>): RequestResult<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError> => (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current Profile
 *
 * Returns details of the currently authenticated operator.
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>): RequestResult<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError> => (options?.client ?? client).get<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

/**
 * Register Patient (Intake)
 *
 * Performs patient intake and demographic registration. SSN is automatically masked.
 */
export const postPatients = <ThrowOnError extends boolean = false>(options: Options<PostPatientsData, ThrowOnError>): RequestResult<PostPatientsResponses, PostPatientsErrors, ThrowOnError> => (options.client ?? client).post<PostPatientsResponses, PostPatientsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Patient Details
 *
 * Retrieves demographic details. Cached in Redis for 1 hour.
 */
export const getPatientsById = <ThrowOnError extends boolean = false>(options: Options<GetPatientsByIdData, ThrowOnError>): RequestResult<GetPatientsByIdResponses, GetPatientsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetPatientsByIdResponses, GetPatientsByIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}',
    ...options
});

/**
 * Update Patient Profile
 *
 * Updates details and evicts the corresponding Redis patient cache entry.
 */
export const putPatientsById = <ThrowOnError extends boolean = false>(options: Options<PutPatientsByIdData, ThrowOnError>): RequestResult<PutPatientsByIdResponses, PutPatientsByIdErrors, ThrowOnError> => (options.client ?? client).put<PutPatientsByIdResponses, PutPatientsByIdErrors, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Search Patients
 *
 * Performs case-insensitive search by patient name.
 */
export const getPatientsSearch = <ThrowOnError extends boolean = false>(options: Options<GetPatientsSearchData, ThrowOnError>): RequestResult<GetPatientsSearchResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPatientsSearchResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/search',
    ...options
});

/**
 * Get Patient Consultation History
 *
 * Retrieves all consultation records for the patient, ordered by date descending. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const getPatientsByIdRecords = <ThrowOnError extends boolean = false>(options: Options<GetPatientsByIdRecordsData, ThrowOnError>): RequestResult<GetPatientsByIdRecordsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPatientsByIdRecordsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}/records',
    ...options
});

/**
 * Add Medical Record
 *
 * Appends a consultation record. Custom assessments/vitals are sent in a dynamic JSON structure. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const postPatientsByIdRecords = <ThrowOnError extends boolean = false>(options: Options<PostPatientsByIdRecordsData, ThrowOnError>): RequestResult<PostPatientsByIdRecordsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostPatientsByIdRecordsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/patients/{id}/records',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Doctors
 *
 * Lists active registered doctors. Cached in Redis for 1 hour.
 */
export const getDoctors = <ThrowOnError extends boolean = false>(options?: Options<GetDoctorsData, ThrowOnError>): RequestResult<GetDoctorsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetDoctorsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/doctors',
    ...options
});

/**
 * Book Appointment
 *
 * Schedules a doctor consultation. Rejects booking if there is a scheduling conflict within a 30-minute window. Uses optimistic locking.
 */
export const postAppointments = <ThrowOnError extends boolean = false>(options: Options<PostAppointmentsData, ThrowOnError>): RequestResult<PostAppointmentsResponses, PostAppointmentsErrors, ThrowOnError> => (options.client ?? client).post<PostAppointmentsResponses, PostAppointmentsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/appointments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Doctor Schedule
 *
 * Lists appointments assigned to the doctor, ordered by time ascending.
 */
export const getAppointmentsDoctorByDoctorId = <ThrowOnError extends boolean = false>(options: Options<GetAppointmentsDoctorByDoctorIdData, ThrowOnError>): RequestResult<GetAppointmentsDoctorByDoctorIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetAppointmentsDoctorByDoctorIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/appointments/doctor/{doctorId}',
    ...options
});

/**
 * Update Appointment Status
 *
 * Transitions slot state (e.g. to CANCELLED). Rejects transition if slot is already cancelled or completed.
 */
export const putAppointmentsByIdStatus = <ThrowOnError extends boolean = false>(options: Options<PutAppointmentsByIdStatusData, ThrowOnError>): RequestResult<PutAppointmentsByIdStatusResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutAppointmentsByIdStatusResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/appointments/{id}/status',
    ...options
});

/**
 * Check-In (Enqueue)
 *
 * Checks in a patient and issues the next sequential token number. Rejects if patient is already active in queue.
 */
export const postQueueCheckIn = <ThrowOnError extends boolean = false>(options: Options<PostQueueCheckInData, ThrowOnError>): RequestResult<PostQueueCheckInResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostQueueCheckInResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/check-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Doctor Queue Lane
 *
 * Retrieves the active queue list (WAITING and ACTIVE) assigned to the doctor.
 */
export const getQueueDoctorByDoctorId = <ThrowOnError extends boolean = false>(options: Options<GetQueueDoctorByDoctorIdData, ThrowOnError>): RequestResult<GetQueueDoctorByDoctorIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetQueueDoctorByDoctorIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/doctor/{doctorId}',
    ...options
});

/**
 * Call Patient
 *
 * Sets status to ACTIVE. Dispatches async SMS notifying the patient to proceed to the room. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const putQueueByIdCall = <ThrowOnError extends boolean = false>(options: Options<PutQueueByIdCallData, ThrowOnError>): RequestResult<PutQueueByIdCallResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutQueueByIdCallResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/{id}/call',
    ...options
});

/**
 * Complete Consultation
 *
 * Sets status to COMPLETED and evicts patient queue item details. Restricted to ROLE_DOCTOR, ROLE_ADMIN.
 */
export const putQueueByIdComplete = <ThrowOnError extends boolean = false>(options: Options<PutQueueByIdCompleteData, ThrowOnError>): RequestResult<PutQueueByIdCompleteResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutQueueByIdCompleteResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'token',
            type: 'apiKey'
        }],
    url: '/queue/{id}/complete',
    ...options
});
