// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080/api' | (string & {});
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type RegisterRequest = {
    username: string;
    password: string;
    role: 'ROLE_ADMIN' | 'ROLE_DOCTOR' | 'ROLE_RECEPTIONIST';
    fullName: string;
};

export type UserResponse = {
    id?: string;
    username?: string;
    role?: string;
    fullName?: string;
};

export type PatientRequest = {
    name: string;
    dateOfBirth: string;
    gender: string;
    ssn: string;
    phone: string;
    email: string;
    bloodType?: string;
    emergencyContactName?: string;
    emergencyContactPhone?: string;
};

export type Patient = {
    id?: string;
    name?: string;
    dateOfBirth?: string;
    gender?: string;
    ssnMasked?: string;
    phone?: string;
    email?: string;
    bloodType?: string;
    emergencyContactName?: string;
    emergencyContactPhone?: string;
};

export type MedicalRecordRequest = {
    conditions: Array<string>;
    allergies: Array<string>;
    vitals: {
        [key: string]: unknown;
    };
};

export type MedicalRecord = {
    id?: string;
    patientId?: string;
    doctorId?: string;
    createdAt?: string;
    conditions?: Array<string>;
    allergies?: Array<string>;
    vitals?: {
        [key: string]: unknown;
    };
};

export type DoctorResponse = {
    id?: string;
    username?: string;
    fullName?: string;
};

export type AppointmentRequest = {
    patientId: string;
    doctorId: string;
    appointmentTime: string;
    notes?: string;
};

export type Appointment = {
    id?: string;
    patientId?: string;
    doctorId?: string;
    appointmentTime?: string;
    status?: string;
    notes?: string;
    version?: number;
};

export type QueueRequest = {
    patientId: string;
    doctorId: string;
};

export type QueueItem = {
    id?: string;
    patientId?: string;
    doctorId?: string;
    tokenNumber?: number;
    status?: string;
    checkedInTime?: string;
};

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Invalid credentials provided.
     */
    401: unknown;
};

export type PostAuthLoginResponses = {
    /**
     * Session established successfully.
     */
    200: UserResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Session terminated, cookie cleared.
     */
    200: unknown;
};

export type PostAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Username already taken or invalid parameters.
     */
    400: {
        error?: string;
    };
    /**
     * Insufficient permissions (requires Admin role).
     */
    403: unknown;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Staff registered successfully.
     */
    201: UserResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Session expired or missing JWT cookie.
     */
    401: unknown;
};

export type GetAuthMeResponses = {
    /**
     * Operator profile details.
     */
    200: UserResponse;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostPatientsData = {
    body: PatientRequest;
    path?: never;
    query?: never;
    url: '/patients';
};

export type PostPatientsErrors = {
    /**
     * Requires ROLE_RECEPTIONIST or ROLE_ADMIN.
     */
    403: unknown;
};

export type PostPatientsResponses = {
    /**
     * Patient registered successfully.
     */
    201: Patient;
};

export type PostPatientsResponse = PostPatientsResponses[keyof PostPatientsResponses];

export type GetPatientsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}';
};

export type GetPatientsByIdErrors = {
    /**
     * Patient not found.
     */
    404: unknown;
};

export type GetPatientsByIdResponses = {
    /**
     * Patient records retrieved.
     */
    200: Patient;
};

export type GetPatientsByIdResponse = GetPatientsByIdResponses[keyof GetPatientsByIdResponses];

export type PutPatientsByIdData = {
    body: PatientRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}';
};

export type PutPatientsByIdErrors = {
    /**
     * Patient not found.
     */
    404: unknown;
};

export type PutPatientsByIdResponses = {
    /**
     * Patient profile updated successfully.
     */
    200: Patient;
};

export type PutPatientsByIdResponse = PutPatientsByIdResponses[keyof PutPatientsByIdResponses];

export type GetPatientsSearchData = {
    body?: never;
    path?: never;
    query: {
        name: string;
    };
    url: '/patients/search';
};

export type GetPatientsSearchResponses = {
    /**
     * Search results array.
     */
    200: Array<Patient>;
};

export type GetPatientsSearchResponse = GetPatientsSearchResponses[keyof GetPatientsSearchResponses];

export type GetPatientsByIdRecordsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}/records';
};

export type GetPatientsByIdRecordsResponses = {
    /**
     * History records array.
     */
    200: Array<MedicalRecord>;
};

export type GetPatientsByIdRecordsResponse = GetPatientsByIdRecordsResponses[keyof GetPatientsByIdRecordsResponses];

export type PostPatientsByIdRecordsData = {
    body: MedicalRecordRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}/records';
};

export type PostPatientsByIdRecordsResponses = {
    /**
     * Consultation record saved.
     */
    201: MedicalRecord;
};

export type PostPatientsByIdRecordsResponse = PostPatientsByIdRecordsResponses[keyof PostPatientsByIdRecordsResponses];

export type GetDoctorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doctors';
};

export type GetDoctorsResponses = {
    /**
     * Active doctor directory list.
     */
    200: Array<DoctorResponse>;
};

export type GetDoctorsResponse = GetDoctorsResponses[keyof GetDoctorsResponses];

export type PostAppointmentsData = {
    body: AppointmentRequest;
    path?: never;
    query?: never;
    url: '/appointments';
};

export type PostAppointmentsErrors = {
    /**
     * Validation errors or scheduling conflict.
     */
    400: unknown;
};

export type PostAppointmentsResponses = {
    /**
     * Appointment booked successfully. Async SMS alert dispatched.
     */
    201: Appointment;
};

export type PostAppointmentsResponse = PostAppointmentsResponses[keyof PostAppointmentsResponses];

export type GetAppointmentsDoctorByDoctorIdData = {
    body?: never;
    path: {
        doctorId: string;
    };
    query?: never;
    url: '/appointments/doctor/{doctorId}';
};

export type GetAppointmentsDoctorByDoctorIdResponses = {
    /**
     * Assigned appointments array.
     */
    200: Array<Appointment>;
};

export type GetAppointmentsDoctorByDoctorIdResponse = GetAppointmentsDoctorByDoctorIdResponses[keyof GetAppointmentsDoctorByDoctorIdResponses];

export type PutAppointmentsByIdStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        status: 'SCHEDULED' | 'CANCELLED' | 'COMPLETED';
    };
    url: '/appointments/{id}/status';
};

export type PutAppointmentsByIdStatusResponses = {
    /**
     * Appointment slot updated.
     */
    200: Appointment;
};

export type PutAppointmentsByIdStatusResponse = PutAppointmentsByIdStatusResponses[keyof PutAppointmentsByIdStatusResponses];

export type PostQueueCheckInData = {
    body: QueueRequest;
    path?: never;
    query?: never;
    url: '/queue/check-in';
};

export type PostQueueCheckInResponses = {
    /**
     * Token issued, queued in WAITING state.
     */
    201: QueueItem;
};

export type PostQueueCheckInResponse = PostQueueCheckInResponses[keyof PostQueueCheckInResponses];

export type GetQueueDoctorByDoctorIdData = {
    body?: never;
    path: {
        doctorId: string;
    };
    query?: never;
    url: '/queue/doctor/{doctorId}';
};

export type GetQueueDoctorByDoctorIdResponses = {
    /**
     * List of active queue items.
     */
    200: Array<QueueItem>;
};

export type GetQueueDoctorByDoctorIdResponse = GetQueueDoctorByDoctorIdResponses[keyof GetQueueDoctorByDoctorIdResponses];

export type PutQueueByIdCallData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/queue/{id}/call';
};

export type PutQueueByIdCallResponses = {
    /**
     * Patient status updated to calling.
     */
    200: QueueItem;
};

export type PutQueueByIdCallResponse = PutQueueByIdCallResponses[keyof PutQueueByIdCallResponses];

export type PutQueueByIdCompleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/queue/{id}/complete';
};

export type PutQueueByIdCompleteResponses = {
    /**
     * Consultation finalized, patient removed from active list.
     */
    200: QueueItem;
};

export type PutQueueByIdCompleteResponse = PutQueueByIdCompleteResponses[keyof PutQueueByIdCompleteResponses];
