// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080/api' | (string & {});
};

export type QueueItem = {
    id?: string;
    patientId?: string;
    doctorId?: string;
    tokenNumber?: number;
    status?: string;
    checkedInTime?: string;
};

export type PatientRequest = {
    name?: string;
    dateOfBirth?: string;
    gender?: string;
    ssn?: string;
    phone?: string;
    email?: string;
    bloodType?: string;
    emergencyContactName?: string;
    emergencyContactPhone?: string;
};

export type Patient = {
    id?: string;
    name?: string;
    dateOfBirth?: string;
    gender?: string;
    ssnMasked?: string;
    phone?: string;
    email?: string;
    bloodType?: string;
    emergencyContactName?: string;
    emergencyContactPhone?: string;
};

export type Appointment = {
    id?: string;
    patientId?: string;
    doctorId?: string;
    appointmentTime?: string;
    status?: string;
    notes?: string;
    version?: number;
};

export type QueueRequest = {
    patientId?: string;
    doctorId?: string;
};

export type MedicalRecordRequest = {
    conditions?: Array<string>;
    allergies?: Array<string>;
    vitals?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type MedicalRecord = {
    id?: string;
    patientId?: string;
    doctorId?: string;
    createdAt?: string;
    conditions?: Array<string>;
    allergies?: Array<string>;
    vitals?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type RegisterRequest = {
    username?: string;
    password?: string;
    role?: string;
    fullName?: string;
};

export type UserResponse = {
    id?: string;
    username?: string;
    role?: string;
    fullName?: string;
};

export type LoginRequest = {
    username?: string;
    password?: string;
};

export type AppointmentRequest = {
    patientId?: string;
    doctorId?: string;
    appointmentTime?: string;
    notes?: string;
};

export type Notification = {
    id?: string;
    userId?: string;
    message?: string;
    channel?: string;
    status?: string;
    createdAt?: string;
};

export type SseEmitter = {
    timeout?: number;
};

export type DoctorResponse = {
    id?: string;
    username?: string;
    fullName?: string;
};

export type CompleteConsultationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/queue/{id}/complete';
};

export type CompleteConsultationResponses = {
    /**
     * OK
     */
    200: QueueItem;
};

export type CompleteConsultationResponse = CompleteConsultationResponses[keyof CompleteConsultationResponses];

export type CallPatientData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/queue/{id}/call';
};

export type CallPatientResponses = {
    /**
     * OK
     */
    200: QueueItem;
};

export type CallPatientResponse = CallPatientResponses[keyof CallPatientResponses];

export type GetPatientByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}';
};

export type GetPatientByIdResponses = {
    /**
     * OK
     */
    200: Patient;
};

export type GetPatientByIdResponse = GetPatientByIdResponses[keyof GetPatientByIdResponses];

export type UpdatePatientData = {
    body: PatientRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}';
};

export type UpdatePatientResponses = {
    /**
     * OK
     */
    200: Patient;
};

export type UpdatePatientResponse = UpdatePatientResponses[keyof UpdatePatientResponses];

export type UpdateAppointmentStatusData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        status: string;
    };
    url: '/appointments/{id}/status';
};

export type UpdateAppointmentStatusResponses = {
    /**
     * OK
     */
    200: Appointment;
};

export type UpdateAppointmentStatusResponse = UpdateAppointmentStatusResponses[keyof UpdateAppointmentStatusResponses];

export type CheckInData = {
    body: QueueRequest;
    path?: never;
    query?: never;
    url: '/queue/check-in';
};

export type CheckInResponses = {
    /**
     * OK
     */
    200: QueueItem;
};

export type CheckInResponse = CheckInResponses[keyof CheckInResponses];

export type RegisterPatientData = {
    body: PatientRequest;
    path?: never;
    query?: never;
    url: '/patients';
};

export type RegisterPatientResponses = {
    /**
     * OK
     */
    200: Patient;
};

export type RegisterPatientResponse = RegisterPatientResponses[keyof RegisterPatientResponses];

export type GetMedicalRecordsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}/records';
};

export type GetMedicalRecordsResponses = {
    /**
     * OK
     */
    200: Array<MedicalRecord>;
};

export type GetMedicalRecordsResponse = GetMedicalRecordsResponses[keyof GetMedicalRecordsResponses];

export type AddMedicalRecordData = {
    body: MedicalRecordRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}/records';
};

export type AddMedicalRecordResponses = {
    /**
     * OK
     */
    200: MedicalRecord;
};

export type AddMedicalRecordResponse = AddMedicalRecordResponses[keyof AddMedicalRecordResponses];

export type MarkAllAsReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/read-all';
};

export type MarkAllAsReadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type BookAppointmentData = {
    body: AppointmentRequest;
    path?: never;
    query?: never;
    url: '/appointments';
};

export type BookAppointmentResponses = {
    /**
     * OK
     */
    200: Appointment;
};

export type BookAppointmentResponse = BookAppointmentResponses[keyof BookAppointmentResponses];

export type GetDoctorQueueData = {
    body?: never;
    path: {
        doctorId: string;
    };
    query?: never;
    url: '/queue/doctor/{doctorId}';
};

export type GetDoctorQueueResponses = {
    /**
     * OK
     */
    200: Array<QueueItem>;
};

export type GetDoctorQueueResponse = GetDoctorQueueResponses[keyof GetDoctorQueueResponses];

export type SearchPatientsData = {
    body?: never;
    path?: never;
    query: {
        name: string;
    };
    url: '/patients/search';
};

export type SearchPatientsResponses = {
    /**
     * OK
     */
    200: Array<Patient>;
};

export type SearchPatientsResponse = SearchPatientsResponses[keyof SearchPatientsResponses];

export type GetUnreadNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/unread';
};

export type GetUnreadNotificationsResponses = {
    /**
     * OK
     */
    200: Array<Notification>;
};

export type GetUnreadNotificationsResponse = GetUnreadNotificationsResponses[keyof GetUnreadNotificationsResponses];

export type SubscribeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notifications/subscribe';
};

export type SubscribeResponses = {
    /**
     * OK
     */
    200: SseEmitter;
};

export type SubscribeResponse = SubscribeResponses[keyof SubscribeResponses];

export type GetDoctorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/doctors';
};

export type GetDoctorsResponses = {
    /**
     * OK
     */
    200: Array<DoctorResponse>;
};

export type GetDoctorsResponse = GetDoctorsResponses[keyof GetDoctorsResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetPatientAppointmentsData = {
    body?: never;
    path: {
        patientId: string;
    };
    query?: never;
    url: '/appointments/patient/{patientId}';
};

export type GetPatientAppointmentsResponses = {
    /**
     * OK
     */
    200: Array<Appointment>;
};

export type GetPatientAppointmentsResponse = GetPatientAppointmentsResponses[keyof GetPatientAppointmentsResponses];

export type GetDoctorAppointmentsData = {
    body?: never;
    path: {
        doctorId: string;
    };
    query?: never;
    url: '/appointments/doctor/{doctorId}';
};

export type GetDoctorAppointmentsResponses = {
    /**
     * OK
     */
    200: Array<Appointment>;
};

export type GetDoctorAppointmentsResponse = GetDoctorAppointmentsResponses[keyof GetDoctorAppointmentsResponses];
